### PR TITLE
Build for aarch64

### PR DESCRIPTION
**Pull request by hfiguiere**
The app runs on a RaspberryPi 400

I had to downgrade sip as sip6 breaks compatibility to build PyQt properly.

### CODE REVIEW

**Comment by Lctrs** [comment]
There are several things I dislike in this (all related to the removal of `pyqt-build`).

Also what does sip6 break ?

**Comment by hfiguiere** [comment]
Simply using the PyQt5 provided build script, instead of knowing how sip works (sip 6 change how it work, so the provided build scripts for PyQt5 don't work). And everything is in the manifest. And no easy way to work around the build issue on aarch64 if "pyqt-build" is used.

**Comment by hfiguiere** [comment]
sip6 command line API is just different.

**Comment by Lctrs** [comment]
`pyqt-build` is only a script to configure the build of PyQt5 using `sip-install` [which is the recommended way of doing things](https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#building-and-installing-from-source).

**Comment by Lctrs** [comment]
Your changes cause PyQt5 not being built anymore with the build flags defined in the runtime (hence [these lines](https://github.com/flathub/org.musicbrainz.Picard/blob/021ad6cbd0286f577df1ea2688001d1629fe52f3/pyqt-build#L24-26)).

As flatpak doesn't resolve environment variables in `config-opts`, we need this file to be able to do it.

**Pull request closed without merging**
