### PR TITLE
Only build on x86_64 & i386 arches

### PR DESCRIPTION
**Pull request by Lctrs**
As building the project fails on other arches.

### CODE REVIEW

**Comment by Lctrs** [comment]
ping @bochecha

**Comment by Lctrs** [comment]
bot, build

**Comment by bochecha** [comment]
What's the failure on other arches, and can't we fix it instead?

**Comment by bochecha** [comment]
> If I remember correctly, PyQt failed to build. Don't know why and didn't have time to look at it.

Please provide a link to build logs.

**Comment by Lctrs** [comment]
Here it is : https://flathub.org/builds/#/builders/2/builds/7155

**Comment by bochecha** [comment]
Ok, so blocking 2.1.1 is obviously bad. Especially since we probably have **very** few users on Aarch64/ARM. (if any)

Let's merge this then, but first please open an issue so we don't forget to fix it eventually. (I also don't have the time right now unfortunately)

**Pull request merged**
