### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by bochecha** [comment]
Hi, thanks for the patch.

I'm curious, why was this necessary? (I would have preferred having that explanation in the commit message)

Also, why did you remove the `--disable-xgrab` for ffmpeg? Is that needed for something?

**Comment by Lctrs** [comment]
Hi.

It's not really necessary. I just like to have latest versions of libs to enjoy bugfixes and all.

Also, it can help the future build of Picard 2.0 - which is already in Beta - by already doing some of the work.

> Also, why did you remove the --disable-xgrab for ffmpeg? Is that needed for something?

`--disable-xgrab` for ffmpeg has been removed in favor of `--disable-libxcb` since ffmpeg 3.3. `--disable-libxcb` is already present in the configuration.

**Comment by bochecha** [comment]
> It's not really necessary. I just like to have latest versions of libs to enjoy bugfixes and all.

Are there actual bug fixes being fixed by those updates? If so, it would be nice to mention it in the commit message. Updating just for the sake of updating is rather uninteresting busywork…

Did you test that the result works? In particular ffmpeg tends to not have a stable API, so I'm always a bit worried when updating it. :worried: 

> --disable-xgrab for ffmpeg has been removed in favor of --disable-libxcb since ffmpeg 3.3. --disable-libxcb is already present in the configuration.

Ok, so I'd like that in its own commit, with this justification in the commit message, please.

**Comment by bochecha** [comment]
So I just had a look at the updates...

* sip: https://www.riverbankcomputing.com/static/Downloads/sip/ChangeLog
    it seems those are mostly docs and test changes, but there are a few bug fixes in there, at least one of which fixes some crashes; there doesn't seem to be any API-breaking change, so that should be relatively safe;
* pyqt4: https://www.riverbankcomputing.com/static/Downloads/PyQt4/ChangeLog
    again, docs and build fixes, with some bug/regression fixes in the middle; this seems extremely safe;
* mutagen: https://github.com/quodlibet/mutagen/blob/master/NEWS#L5-L37
    this seems relatively safe; the only breaking change I see is the removed support for Python 3.3, but Picard builds with Python2 anyway;
* chromaprint: https://github.com/acoustid/chromaprint/releases/tag/v1.4.3
    there seems to be some API-breaking changes here (the return code of a CLI tool is API, and AFAIK Picard only uses the fpcalc CLI tool), so this requires careful testing;
* ffmpeg: changing ffmpeg branches like this is always worrying, because of the lack of API/ABI guarantees from upstream; however, Picard doesn't use ffmpeg directly IIRC, it's only chromaprint that does; so maybe this is safe, as long as it doesn't break chromaprint?

All in all, this needs careful testing, but it seems like it might not break anything. If you did test it (especially the part involving chromaprint/ffmpeg) and things worked, then that's enough for me. :slightly_smiling_face:

**Comment by Lctrs** [comment]
For what I tested, things works as expected.

**Comment by bochecha** [comment]
I just realized you removed the aarch64 patch. Is it not necessary any more ?

**Comment by Lctrs** [comment]
It has been moved into `shared-modules`. So it's not necessary since a while.

**Comment by bochecha** [comment]
> It has been moved into shared-modules. So it's not necessary since a while.

Indeed… And I moved it there myself. >_<

I'd also like this to be in its own commit, with an explanation for why that's not necessary any more.

**Comment by Lctrs** [comment]
You mean new PR ? Or different commits in this PR ?

**Comment by bochecha** [comment]
I meant rebasing this PR. I'm happy to help you with that if you need. :slightly_smiling_face:

**Comment by Lctrs** [comment]
I must admit I have no idea what you have in mind.

**Comment by bochecha** [comment]
I mean using `git rebase -i` to split your commit into 3.

I'll do it, no worries. :slightly_smiling_face:

**Comment by bochecha** [comment]
Alright, I split this into 2 commits (preserving your authorship, because you're the one who did the work! :slightly_smiling_face: ), and pushed it to master.

It's building now: https://flathub.org/builds/#/builders/2/builds/89

Thanks!

**Pull request closed without merging**
