### PR TITLE
Add the missing libdiscid modules

### LINKED ISSUE #6: Missing discid
See https://community.metabrainz.org/t/discid-missing-on-my-ubuntu-16-04/351056/2

Would be nice if people encountering issues reported them… :disappointed: 

This came up in the Picard 2.0 discussion (#5)

### PR DESCRIPTION
**Pull request by bochecha**
Thanks @Lctrs for mentioning it was missing!

Fixes #6

### CODE REVIEW

**Comment by Lctrs** [comment]
I'm notre familiar with Flatpak's permissions but maybe we need to allow the application to use the CD reader in the `finish-args` section. WDYT @bochecha ?

**Comment by bochecha** [comment]
@Lctrs that's very likely, yes.

Unfortunately that means using `"finish-args": ["--device=all"]`, which is pretty awful.  :disappointed:

**Comment by Lctrs** [comment]
Even with this, I'm not sure it will work at all. See https://github.com/flatpak/flatpak/issues/12. :/

**Comment by bochecha** [comment]
I was told it should work, Picard will get access to the CD/DVD device with `--device=all`, as long as that CD/DVD was inserted **before** starting the app.

That is, we get access, but no hotplug.

**Pull request merged**
