### PR TITLE
Forward build flags to SIP and PyQt

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by Lctrs** [comment]
cc @bochecha

**Comment by bochecha** [comment]
What is this for? Your commit message doesn't explain what this does.

**Comment by Lctrs** [comment]
SIP and PyQt are ignoring `CFLAGS`, `CXXFLAGS`, and `LDFLAGS` env variables for defining the build flags. Doing this ensure that they're build with the same build flags as defined in `freedesktop-sdk`.

**Comment by bochecha** [comment]
> SIP and PyQt are ignoring `CFLAGS`, `CXXFLAGS`, and `LDFLAGS` env variables for defining the build flags. Doing this ensure that they're build with the same build flags as defined in `freedesktop-sdk`.

That's good. Please mark that in the commit message. :wink:

**Pull request merged**
